### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by camilousa** [camilousa/correo#2]
Cuando se deja el host por defecto(outlook)  sale el siguiente error:
Error enviando correos: Traceback (most recent call last): File "sendEmail.py", line 113, in main smtp = start_server(host, port, source_address, password) File "sendEmail.py", line 69, in start_server smtp.starttls() File "/usr/lib/python3.8/smtplib.py", line 762, in starttls self.ehlo_or_helo_if_needed() File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed if not (200 <= self.ehlo()[0] <= 299): File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo self.putcmd(self.ehlo_msg, name or self.local_hostname) File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd self.send(str) File "/usr/lib/python3.8/smtplib.py", line 363, in send raise SMTPServerDisconnected('please run connect() first') smtplib.SMTPServerDisconnected: please run connect() first

Luego de hacerle seguimiento encontré que las variables host y password están llegando en None a start_server

**Comment by ssierrac** [comment]
Las variables del servidor de correo las toma del archivo .env, el nombre de las variables que debe tener el archivo se encuentra en el  **README**. En el pull request #3 ahora se comprueba que las variables no lleguen vacías, de ser así, se piden por terminal de comandos.


Ejemplo de ejecución debug:
```zsh
python sendEmail.py sample_data/Aprendizaje-máquina-corte2.xlsx mlcorte2 template_camilo.html --host gmail -d
```


Ejemplo de ejecución con envio del correo:
```zsh
python sendEmail.py sample_data/Aprendizaje-máquina-corte2.xlsx mlcorte2 template_camilo.html --host outlook
```
